In [4]:
# 1. How do you handle duplicate values in a dataset in Python?

In [5]:
import numpy as np
import pandas as pd

In [6]:
arr = np.array([1,2,3,4,5,5])

In [7]:
print np.unique(arr)

SyntaxError: invalid syntax (<ipython-input-7-002c64e40e9e>, line 1)

In [8]:
print np.unique([1,2,3,4,5,5])

SyntaxError: invalid syntax (<ipython-input-8-26cbaabd008a>, line 1)

In [9]:
import numpy as np

In [10]:
print np.unique([1,2,3,4,5,5])

SyntaxError: invalid syntax (<ipython-input-10-26cbaabd008a>, line 1)

In [11]:
print arr

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(arr)? (<ipython-input-11-bb090780799d>, line 1)

In [12]:
print(arr)

[1 2 3 4 5 5]


In [13]:
print (np.unique([1,2,3,4,5,5]))

[1 2 3 4 5]


In [14]:
print(np.unique(arr))

[1 2 3 4 5]


In [15]:
df = pd.DataFrame([1,2,3],[1,2,3],[2,3,4,5],[3,4,5,6])

TypeError: data type not understood

In [16]:
df = pd.DataFrame([1,2,3],[1,2,3],[2,3,4],[3,4,5])

TypeError: data type not understood

In [17]:
df = pd.DataFrame([1,2,3,4,5])

In [18]:
print(df)

   0
0  1
1  2
2  3
3  4
4  5


In [19]:
data = [['Alex',10],['Bob',12],['Clarke',13]]

In [20]:
df = pd.DataFrame(data)

In [21]:
print(df)

        0   1
0    Alex  10
1     Bob  12
2  Clarke  13


In [22]:
data = [['Alex',10],['Alex',10],['Clarke',13]]

In [23]:
df = pd.DataFrame(data)

In [24]:
df.drop_duplicates()

0   1
0    Alex  10
2  Clarke  13

In [25]:
print(df)

        0   1
0    Alex  10
1    Alex  10
2  Clarke  13


In [26]:
# 2. You are given two tables - friend_request and request_accepted. 
# Friend_request contains requester_id, time and sent_to_id and request_accepted table contains time, acceptor_id and requestor_id.
# How will you determine the overall acceptance rate of requests? 

In [27]:
friend_request = pd.DataFrame(
    {"requester_id":[1001,1002,1003],
     "time":["2017-07-01","2017-07-02","2017-07-03"],
     "receiver_id":[3001,3002,3003]}
)

request_accepted = pd.DataFrame(
    {"requester_id":[1001,1003],
     "time":["2017-07-01","2017-07-04"],
     "acceptor_id":[3001,3003]}
)

In [28]:
rate = len(friend_request["requester_id"])/len(request_accepted["requester_id"])

In [29]:
print(rate)

1.5


In [30]:
rate = len(request_accepted["requester_id"])/len(friend_request["requester_id"])

In [31]:
print(rate)

0.6666666666666666


In [32]:
# 3. identify credit card

In [42]:
def verfiyCredit(c):
        if len(c)==16: 
            if c[0]==4:
                print("VISA")
            if(c[0:4] == "4026" or c[0:4] == "4405" or c[0:4] == "4508" or c[0:4] == "4844" or c[0:4] == "4913" or c[0:4] == "4917"  
            or c[0:6] == "417500"):
                print("VISAELECTRON")
        elif len(c)==15 and ((c[0:2] == "34" or c[0:2] == "37")):
            print("AMEX")
        elif len(c) == 14 and ((c[0:2] == "36")):
            print("Diners Club")

In [43]:
creditCard = ["4175004175004172","4917491749174917","346416800707698","376416800707698","37641680070769832112","36641680070769","54545641680070769"]
for c in creditCard:
    verfiyCredit(c)

VISAELECTRON
VISAELECTRON
AMEX
AMEX
Diners Club


In [44]:
# 4. write a Python function called PrintCumulativeTimeSeries().

In [ ]:
def PrintCumulativeTimeSeries(expId, country, vertical):
    